name: Deploy to EC2

on:
  push:
    branches: [main]
    paths:
      - "web/**" # web 디렉토리 변경사항만 감지

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web # 작업 디렉토리 설정
    steps:
      - uses: actions/checkout@v4

      # 의존성 설치 및 빌드
      - name: Install dependencies
        run: |
          npm install

      - name: Build project
        run: |
          npm run build

      # Docker Hub 로그인
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: web
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/mycarforme-frontend:latest

      # EC2에 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 기존 컨테이너 중지 및 삭제
            docker stop frontend-container || true
            docker rm frontend-container || true

            # 사용하지 않는 이미지 삭제
            docker image prune -af

            # EC2에서 Docker 이미지 풀
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/mycarforme-frontend:latest

            # 새 컨테이너 실행
            docker run -d --name frontend-container -v /etc/letsencrypt:/etc/letsencrypt -p 80:80 -p 443:443 ${{ secrets.DOCKER_HUB_USERNAME }}/mycarforme-frontend:latest
